version: "3.9"
services:
  memes:
    build: services/memes
    container_name: memes
    restart: unless-stopped
    command: ["python", "src/memes/presentation/api"]
    volumes:
      - ./services/memes:/memes
    networks:
      - main-network
    environment:
      PUBLIC_URL: http://localhost
      MEDIA_SSL: false
      MEDIA_HOST: media
      MEDIA_PORT: 8000
      POSTGRES_DATABASE: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_ECHO: false
    depends_on:
      - postgres
      - media

  media:
    build: services/media
    container_name: media
    restart: unless-stopped
    command: ["python", "src/media/presentation/api"]
    volumes:
      - ./services/media:/media
    networks:
      - main-network
    environment:
      MINIO_SERVER: minio
      MINIO_ACCESS_KEY: access-key
      MINIO_SECRET_KEY: secret-key
    depends_on:
      - minio

  nginx:
    image: nginx:alpine
    container_name: meme-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main-network
    ports:
      - 80:80

  postgres:
    image: postgres:alpine
    container_name: meme-postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main-network
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  minio:
    image: bitnami/minio:2024.7.16
    container_name: meme-minio
    restart: unless-stopped
    volumes:
      - minio_data:/bitnami/minio/data
    networks:
      - main-network

networks:
  main-network:
    driver: bridge

volumes:
  postgres_data: null
  minio_data: null
